export const projectData = [
  {
    supervisorName: "Dr. Abbas Yehia, Mohamed Darweesh",
    supervisorEmail: "abbas.yehia@guc.edu.eg",
    department: "Materials Engineering",
    projectTitle: "Characterization of rubber blends (Butyl rubber/EPDM)",
    researchField: "Materials Science and Engineering",
    projectDescription: "Blending polymers, such as Butyl rubber and EPDM, can produce new materials with improved properties not present in the individual constituents.",
    projectMethodology: "1. Select and weigh polymers\n2. Mix using a prabender with a humanizer\n3. Cure the blend\n4. Evaluate blend properties",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Materials Engineering"]
  },
  {
    supervisorName: "Dr. Abbas Yehia",
    supervisorEmail: "abbas.yehia@guc.edu.eg",
    department: "Materials Science",
    projectTitle: "Determination of life aging of styrene butadiene rubber products",
    researchField: "Materials Science and Engineering",
    projectDescription: "Study the effects of deteriorating agents like heat and stress on the lifespan of rubber products.",
    projectMethodology: "1. Select rubber type\n2. Mix with specific additives\n3. Cure the rubber\n4. Determine stress/strain properties\n5. Use Arrhenius equation for lifetime calculation",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Materials Science and Engineering"]
  },
  {
    supervisorName: "Dr. Abbas Yehia, Dr. Shash",
    supervisorEmail: "abbas.yehia@guc.edu.eg",
    department: "Materials Engineering and Design and Production Engineering",
    projectTitle: "Determination of the softening point of plastics",
    researchField: "Materials Science and Engineering",
    projectDescription: "Develop a system to determine the softening point of plastics through temperature programming and mechanical setup.",
    projectMethodology: "1. Obtain temperature-controlled oven\n2. Design sample holder\n3. Fix dial and start heating\n4. Record softening temperature",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Design and Production Engineering", "Materials Engineering"]
  },
  {
    supervisorName: "Prof. Dr. Ahmed Abd El Aziz",
    supervisorEmail: "ahmed.aziz@guc.edu.eg",
    department: "Materials Engineering",
    projectTitle: "Surface modification of biodegradable materials using plasma electrolytic oxidation for orthopedic implants",
    researchField: "Biomaterials and Corrosion",
    projectDescription: "Utilize plasma electrolytic oxidation to protect light alloys, improving biocompatibility and wear resistance for orthopedic implants.",
    projectMethodology: "- Design PEO system cell\n- Test the PEO system\n- Characterize coating layer degradation in simulated body fluid and wear resistance",
    qualifications: "Knowledge of corrosion and human biodegradable implants",
    furtherComments: "One student",
    eligibleDepartments: ["Design and Production Engineering", "Materials Engineering", "Mechatronics Engineering"]
  },
  {
    supervisorName: "Prof. Dr. Ahmed Abd El Aziz",
    supervisorEmail: "ahmed.aziz@guc.edu.eg",
    department: "Materials Engineering",
    projectTitle: "Construction and parameter control of delta 3D printing for furniture",
    researchField: "Materials and Design",
    projectDescription: "Design a delta 3D printer to produce furniture from agricultural waste, focusing on sustainability.",
    projectMethodology: "- Construct delta 3D printer\n- Develop printer software\n- Validate printing parameters\n- Print a furniture model",
    qualifications: "Knowledge of programming and 3D printing",
    furtherComments: "One student",
    eligibleDepartments: ["Design and Production Engineering", "Materials Engineering", "Mechatronics Engineering"]
  },
  {
    supervisorName: "Prof. Dr. Ahmed Abd El Aziz",
    supervisorEmail: "ahmed.aziz@guc.edu.eg",
    department: "Materials Engineering",
    projectTitle: "Construction of extruder for 3D printing of furniture",
    researchField: "Materials and Design",
    projectDescription: "Develop a 3D printing extruder system utilizing agricultural waste for eco-friendly production.",
    projectMethodology: "- Design and construct extruder\n- Mount on 3D printer\n- Print a furniture model",
    qualifications: "Knowledge of materials selection, design, and simulation",
    furtherComments: "One student",
    eligibleDepartments: ["Design and Production Engineering", "Materials Engineering", "Mechatronics Engineering"]
  },
  {
    supervisorName: "Prof. Dr. Ahmed Abd El Aziz",
    supervisorEmail: "ahmed.aziz@guc.edu.eg",
    department: "Materials Engineering",
    projectTitle: "Recent development in green hydrogen production for Fuel Cells",
    researchField: "Green Energy Solution",
    projectDescription: "Develop nano-porous catalysts for hydrogen production using dealloying techniques.",
    projectMethodology: "- Fabricate Ni nano-porous catalyst\n- Compare with commercial Ni foam catalyst\n- Test efficiency for hydrogen production",
    qualifications: "Knowledge of fuel cell design and renewable energy",
    furtherComments: "One student",
    eligibleDepartments: ["Design and Production Engineering", "Materials Engineering", "Mechatronics Engineering"]
  },
  {
    supervisorName: "Prof. Dr. Ahmed Abd El Aziz, Dr. Anke Klingner",
    supervisorEmail: "ahmed.aziz@guc.edu.eg",
    department: "Materials Engineering",
    projectTitle: "Electrospun nanofibers decorated with silver nanoparticles for wound healing",
    researchField: "Materials and Design",
    projectDescription: "Produce polymeric nanofibers with silver nanoparticles for biomedical applications like wound healing.",
    projectMethodology: "- Select suitable polymers and materials\n- Employ electrospinning techniques\n- Prepare silver nanoparticles",
    qualifications: "Knowledge of nanotechnology and materials selection",
    furtherComments: "One student",
    eligibleDepartments: ["Design and Production Engineering", "Materials Engineering", "Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Abbas Yehia, Dr. Amir Roushdy",
    supervisorEmail: "abbas.yehia@guc.edu.eg",
    department: "Materials Engineering and Mechatronics Engineering",
    projectTitle: "Optimization of rubber additives in Styrene butadiene rubber",
    researchField: "Materials Science and Engineering",
    projectDescription: "Optimize additive concentrations in rubber to enhance performance.",
    projectMethodology: "- Weigh additives\n- Mix materials using a roll mixer\n- Cure at 150°C\n- Determine physico-mechanical properties",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Materials Engineering", "Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a miniature car-like robot and a software framework for single-agent robotics and control",
    researchField: "Control Systems",
    projectDescription: "This project involves designing a compact car-like robot tailored for exploring single-agent robotic systems. The robot will be equipped with sensors, actuators, and an onboard computing system. The goal is to develop a modular software framework that supports control algorithms to enable tasks like path following, obstacle avoidance, and dynamic control in real-world environments.",
    projectMethodology: "1. Develop a CAD model of the robot and choose sensors (e.g., LiDAR, IMU) and actuators\n2. Assemble the robot with embedded hardware\n3. Create a modular framework using Python/ROS for real-time control\n4. Implement control algorithms like PID or MPC\n5. Test the robot's navigation and control in a controlled environment",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Model Predictive Control of a Mobile Robot",
    researchField: "Control Systems",
    projectDescription: "This project focuses on applying Model Predictive Control (MPC) to a mobile robot for optimal navigation and control. MPC will ensure the robot follows desired trajectories while avoiding obstacles and accounting for system constraints.",
    projectMethodology: "1. Derive a mathematical model of the robot dynamics\n2. Formulate the cost function and constraints for the MPC problem\n3. Use MATLAB or Python to simulate the robot's motion with MPC\n4. Deploy the controller on a mobile robot\n5. Compare performance with traditional control strategies like PID",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a miniature car-like robot and a software framework for single-agent robotics and estimation",
    researchField: "Control Systems",
    projectDescription: "This project aims to design a small-scale car-like robot integrated with a software framework for implementing state estimation techniques, such as Kalman Filters, to enhance localization and navigation capabilities.",
    projectMethodology: "1. Design and build the robot with sensors (e.g., GPS, encoders)\n2. Create software for fusing sensor data and state estimation algorithms\n3. Implement Kalman/Extended Kalman Filters for localization\n4. Validate estimation accuracy in simulated and real-world settings",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a miniature car-like robot and a software framework for multi-agent coordination",
    researchField: "Control Systems",
    projectDescription: "This project develops a fleet of small car-like robots and a software framework to study multi-agent coordination problems such as consensus, formation control, and distributed task allocation.",
    projectMethodology: "1. Build multiple robots with communication modules\n2. Design distributed algorithms for communication and coordination\n3. Implement consensus algorithms like the leader-follower model\n4. Validate coordination tasks in simulation and real-world environments",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Centralized MPC for consensus of multi-agent systems",
    researchField: "Control Systems",
    projectDescription: "This project explores a centralized Model Predictive Control (MPC) approach to achieve consensus among multiple agents, optimizing their actions collectively to align states or achieve formation while considering system constraints.",
    projectMethodology: "1. Represent agent dynamics and interactions in a centralized framework\n2. Formulate a global cost function for consensus with constraints\n3. Test scenarios like formation control and synchronization using tools like MATLAB or Python\n4. Evaluate performance in terms of convergence, computational load, and robustness",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Distributed MPC for consensus of multi-agent systems",
    researchField: "Control Systems",
    projectDescription: "This project explores the use of Distributed Model Predictive Control (DMPC) for achieving consensus in multi-agent systems, focusing on scenarios like formation control or flocking.",
    projectMethodology: "1. Model agent dynamics and interaction topology\n2. Formulate local and global optimization problems for agents\n3. Implement distributed solvers for the consensus problem\n4. Test DMPC in a simulated multi-agent environment",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a networked control system under network imperfections using MPC",
    researchField: "Control Systems",
    projectDescription: "This project examines the design of a networked control system where data exchange occurs over a communication network. Model Predictive Control (MPC) is used to handle challenges posed by network imperfections like latency, packet loss, and jitter.",
    projectMethodology: "1. Develop a model incorporating network delays and imperfections\n2. Modify MPC algorithms to account for network disturbances\n3. Validate performance using tools like Simulink or Python\n4. Test on a physical system with a networked control setup",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of Networked Multi-Agents under network imperfections using MPC",
    researchField: "Control Systems",
    projectDescription: "This project focuses on controlling a group of networked agents under communication imperfections. MPC will be applied to ensure coordinated behavior while compensating for issues like delays and data loss.",
    projectMethodology: "1. Define dynamics and inter-agent communication models\n2. Design an MPC controller to address network issues\n3. Test scenarios with imperfect communication in a simulated environment\n4. Deploy the system on physical agents",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a miniature UAV and a software framework for single-agent robotics and control",
    researchField: "Control Systems",
    projectDescription: "This project involves designing a small Unmanned Aerial Vehicle (UAV) to study single-agent robotics and control. The UAV will integrate sensors, actuators, and control algorithms to perform tasks like stable hovering, trajectory tracking, and obstacle avoidance.",
    projectMethodology: "1. Create a lightweight UAV frame and equip it with necessary sensors (IMU, barometer) and actuators\n2. Develop a software framework for flight control and navigation\n3. Apply PID or MPC for stability and path tracking\n4. Validate performance through indoor and outdoor flight experiments",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Model Predictive Control of a miniature UAV",
    researchField: "Control Systems",
    projectDescription: "This project applies Model Predictive Control (MPC) to a miniature UAV to achieve precise control in trajectory following, stabilization, and obstacle avoidance while accounting for system constraints.",
    projectMethodology: "1. Derive UAV dynamics considering constraints like motor limits\n2. Develop an MPC framework to solve the optimization problem in real-time\n3. Use MATLAB/Simulink or Python for flight simulations\n4. Deploy the controller on a real UAV platform\n5. Test and compare with traditional control methods",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a miniature UAV and a software framework for single-agent robotics and estimation",
    researchField: "Control Systems",
    projectDescription: "This project designs a miniature UAV integrated with a software framework for state estimation, enabling precise localization and control in challenging environments.",
    projectMethodology: "1. Assemble a UAV with suitable sensors (GPS, IMU)\n2. Implement state estimation algorithms like Kalman Filters\n3. Test estimation performance in software environments\n4. Evaluate the UAV's localization accuracy in real-world conditions",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Design of a miniature UAV and a software framework for multi-agent coordination",
    researchField: "Control Systems",
    projectDescription: "This project involves designing multiple miniature UAVs and a software framework for exploring multi-agent coordination tasks, such as formation control and collaborative navigation.",
    projectMethodology: "1. Build UAVs equipped with communication modules\n2. Implement algorithms for inter-UAV communication and coordination\n3. Use distributed control techniques for tasks like formation flying\n4. Validate coordination in simulated and physical environments",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Simulation and implementation of a Flying Ad-hoc Network for Air to Air Communication of Micro Aerial Vehicles",
    researchField: "Control Systems",
    projectDescription: "This project explores the creation of a Flying Ad-hoc Network (FANET) for UAVs, enabling robust air-to-air communication. The system focuses on dynamic network topology, low latency, and reliability.",
    projectMethodology: "1. Simulate FANET protocols in NS-3 or OMNeT++\n2. Optimize routing protocols for air-to-air communication\n3. Deploy on UAVs equipped with communication modules\n4. Test performance in various mission scenarios",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Simulation and implementation of a Vehicular Ad-hoc Network for car-to-car mobile Communication and networking",
    researchField: "Control Systems",
    projectDescription: "This project investigates the development of a Vehicular Ad-hoc Network (VANET) to enable real-time car-to-car communication for safety, navigation, and coordination in traffic systems.",
    projectMethodology: "1. Use tools like SUMO or NS-3 to model VANETs\n2. Develop efficient routing protocols for vehicular communication\n3. Deploy the VANET system on car-like robots or simulators\n4. Validate in scenarios like collision avoidance and traffic optimization",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "System identification of network imperfections using machine learning",
    researchField: "Control Systems",
    projectDescription: "This project uses machine learning techniques to identify and model imperfections in communication networks, such as latency and packet loss.",
    projectMethodology: "1. Gather network performance data\n2. Identify key features affecting network quality\n3. Train machine learning models to predict imperfections\n4. Test model accuracy on new data sets",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "System identification of network imperfections using neural networks",
    researchField: "Control Systems",
    projectDescription: "This project applies neural networks to model and predict network imperfections, aiming for better system performance under variable network conditions.",
    projectMethodology: "1. Preprocess network data for training\n2. Build neural network architectures for system identification\n3. Train using techniques like backpropagation\n4. Evaluate on unseen network conditions",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Distributed control of multi-robot partially observable Markov decision processes",
    researchField: "Control Systems",
    projectDescription: "This project addresses distributed control for multi-robot systems operating under POMDPs, enabling robots to make decisions with incomplete information.",
    projectMethodology: "1. Define state, actions, and observation spaces for robots\n2. Implement distributed solvers for POMDPs\n3. Test scenarios with limited observation\n4. Deploy in real-world multi-robot setups",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Consensus Control for Partially Observable Multi-vehicle Systems",
    researchField: "Control Systems",
    projectDescription: "This project develops consensus control strategies for multi-vehicle systems operating in environments with partial observability.",
    projectMethodology: "1. Define dynamics and observation models\n2. Develop algorithms for achieving consensus under uncertainty\n3. Use tools like MATLAB or Python for validation\n4. Test with physical vehicles",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Distributed Control of Quadrotor Swarms with Multi-agent Reinforcement Learning algorithms",
    researchField: "Control Systems",
    projectDescription: "This project leverages multi-agent reinforcement learning (MARL) to enable distributed control of quadrotor swarms for tasks like formation flying and collaborative exploration.",
    projectMethodology: "1. Simulate quadrotor dynamics and swarm behavior\n2. Train MARL agents using techniques like Q-learning\n3. Validate performance in tasks like obstacle avoidance\n4. Test on quadrotor swarms in controlled environments",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Ayman El-Badawy",
    supervisorEmail: "ayman.elbadawy@guc.edu.eg",
    department: "Mechatronics Engineering",
    projectTitle: "Distributed Control of miniature-car like robots with Multi-agent Reinforcement Learning algorithms",
    researchField: "Control Systems",
    projectDescription: "This project explores MARL for distributed control of car-like robots, enabling them to coordinate in tasks like traffic management or collaborative navigation.",
    projectMethodology: "1. Simulate car dynamics and interactions\n2. Train agents using MARL frameworks\n3. Validate in realistic traffic scenarios\n4. Deploy algorithms on miniature car robots",
    qualifications: "Must be eligible to undertake a B.Sc. thesis in Mechatronics Engineering",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "IoT Based Smart Energy Meter",
    researchField: "Smart Grids/Embedded Systems",
    projectDescription: "By utilizing embedded systems technology, this thesis focuses on the design and implementation of a prototype for a smart energy meter that can monitor, record, analyze, and control electricity consumption in real-time in a smart home. The prototype will have capabilities such as communicating with the customer to provide real-time data about electricity consumption.",
    projectMethodology: "1. Research\n2. Simulations\n3. Hardware Implementation",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "Auxiliary Control of Electric Vehicles Via Embedded Systems",
    researchField: "Electric Vehicles/Embedded Systems",
    projectDescription: "Electric vehicles have several auxiliary systems that assist safe and comfortable driving. Among these systems are the automatic vehicle speed controller, lane change assisting system, and parking assisting system. The objective of this project is to design and implement a prototype for different auxiliary control systems for electric vehicles.",
    projectMethodology: "1. Research\n2. Simulations\n3. Hardware Implementation",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "Rule-Based Energy Management System for Plug-in-Hybrid Electric Vehicles",
    researchField: "Hybrid Electric Vehicles",
    projectDescription: "Hybrid Electric Vehicles have an electric motor (EM) to assist the operation of the internal combustion engine (ICE), aiming to reduce fuel consumption. This thesis develops and simulates a rule-based strategy for power split between the EM and ICE based on vehicle parameters, reducing fuel consumption while preserving battery life.",
    projectMethodology: "1. Research\n2. Simulations",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "Optimal Energy Management System for Plug-in-Hybrid Electric Vehicles",
    researchField: "Hybrid Electric Vehicles",
    projectDescription: "This thesis aims to optimize the power/torque split in Hybrid Electric Vehicles between the electric motor and the internal combustion engine to reduce fuel consumption. The problem is formulated as an optimization problem and solved using suitable techniques, validated through various case studies.",
    projectMethodology: "1. Research\n2. Simulations",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "Modeling and Analysis of a Dual Motor Electric Vehicle",
    researchField: "Electric Vehicles",
    projectDescription: "This bachelor thesis develops and analyzes a comprehensive model of a dual motor electric vehicle, focusing on understanding the dynamics and performance characteristics powered by two independent motors for improved traction, acceleration, and power distribution.",
    projectMethodology: "1. Research\n2. Simulations",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "Control of a Single Motor Battery Electric Vehicle",
    researchField: "Electric Vehicles",
    projectDescription: "This bachelor project develops and controls a model of a single motor electric vehicle, focusing on understanding its dynamics and performance while designing a battery management system.",
    projectMethodology: "1. Research\n2. Simulations",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },
  {
    supervisorName: "Dr. Walid Omran / Prof. Nahed ELmahallawy",
    supervisorEmail: "walid.omran@guc.edu.eg",
    department: "Mechatronics",
    projectTitle: "Solar Based Battery Charging System for Electric Vehicles",
    researchField: "Renewable Energy/Electric Vehicles",
    projectDescription: "Photovoltaic (PV) systems utilize sunlight to generate DC electric power, which can charge energy storage batteries. This thesis designs and simulates a PV system for charging electric vehicle batteries, considering weather and loading conditions.",
    projectMethodology: "1. Research\n2. Simulations\n3. (Possible hardware implementation)",
    qualifications: "N/A",
    furtherComments: "N/A",
    eligibleDepartments: ["Mechatronics Engineering"]
  },        
];
